DROP TABLE IF EXISTS ODONTOLOGOS;

CREATE TABLE ODONTOLOGOS
(
    ID           INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE       VARCHAR(255),
    APELLIDO     VARCHAR(255),
    MATRICULA    VARCHAR(255)
);


